### ISSUE TITLE
Suggestions needed - Move SDXL model download to host rather than inside docker?

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#195]
Should we implementing this change as it would reduce the waiting time and the amount of data needed for model downloads each time the Docker container is built?

**Comment by arjunsuresh** [comment]
Hi @anandhu-eng this is a nice thing to do but we should make it optional using `enable_if_env` so that by default download happens inside docker and host system is untouched. Also, for nvidia-implementation since scratch space is used and mounted from host, once a successful download happens and is copied to the scratch path, there won't be a redownload even when new container images are run.

**Comment by anandhu-eng** [comment]
Thank you @arjunsuresh , currently i think its still soft linking the download folder for NVIDIA SDXL. 

I'm assigning this to myself.

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , I'm having a doubt regarding the following statement:
> once a successful download happens and is copied to the scratch path, there won't be a redownload even when new container images are run.

Is it not the case that this behavior applies only to model downloads through the make command specified in the NVIDIA documentation and not to model downloads conducted through cm scripts?
