### ISSUE TITLE
Significant Performance Decrease Running CM vs Source

### ISSUE THREAD

**Issue by zixianwang2022** [mlcommons/cm4mlops#532]
Hi, 

We are observing a significant performance decrease when we are running with CM scripts vs. running in command line of the model. 

CM Run script on SDXL for 500 samples
```
cm run script --tags=run-mlperf,inference,_r4.1-dev,_scc24-main   --model=sdxl   --framework=pytorch   --category=datacenter   --scenario=Offline   --execution_mode=test   --device=rocm   --quiet --precision=float16   --adr.mlperf-implementation.tags=_branch.test,_repo.https://github.com/zixianwang2022/mlperf-scc24 --adr.mlperf-implementation.version=custom  --env.CM_GET_PLATFORM_DETAILS=no
```
Throughput: 0.58. 

Running from source: 
```
python3 main.py --dataset "coco-1024" --dataset-path coco2014 --profile stable-diffusion-xl-pytorch --model-path /work1/zixian/ziw081/CM/models/SDXL/official_pytorch/fp16/stable_diffusion_fp16/ --dtype fp16 --device cuda --time 30 --scenario Offline --max-batchsize 1
```
Throughput: 0.763552. 

In my running from source, user.conf contains: 
```
stable-diffusion-xl.Offline.min_query_count = 500
stable-diffusion-xl.Offline.max_query_count = 500
```

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022 `time` is not an allowed parameter to be changed as it [changes](https://github.com/mlcommons/inference/blob/master/text_to_image/main.py#L456) the run duration. Without using this parameter are you seeing any performance difference? While using CM, you can see the exact `python main.py` call being printed to the console and you can see if there are any other difference from the normal run.

**Comment by zixianwang2022** [comment]
Thank you @arjunsuresh , 

When I rerun from command line without using `--time`, we are seeing a **even better** improvement over our previous command line run. It doesn't seem to be the issue with `--time`.

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022 as I told in the previous comment, you can see on console the exact command CM is generating. After that the same command is run on the shell and so the only chances of performance difference are

1. Some run parameters in the command are different 
2. Version of torch or any performance relevant dependency like torch are different. The version info for the CM run can be seen [here](https://github.com/zixianwang2022/cm4mlperf-inference/blob/mlperf-inference-results-scc24/open/UCSD/measurements/aqua-reference-rocm-pytorch-v2.6.0.dev20241109-scc24-base/stable-diffusion-xl/offline/cm-version-info.json)

Meanwhile since you are running on AMD GPUs, adding a script similar to [this](https://github.com/mlcommons/cm4mlops/tree/main/script/get-cuda-devices) for AMD GPUs will be a valuable contribution for the competition. Currently the accelerator details are coming [empty](https://github.com/zixianwang2022/cm4mlperf-inference/blob/mlperf-inference-results-scc24/open/UCSD/systems/aqua-reference-rocm-pytorch-v2.6.0.dev20241109-scc24-base.json#L2)

**Comment by Henryfzh** [comment]
Hi, @arjunsuresh, I have done the detect.py for ROCm devices. How do I test if the script works? Also, how do I update the .yaml file in the folder?

**Comment by arjunsuresh** [comment]
That's great @Henryfzh. You can do

```
cd $HOME/CM/repos/mlcommons@cm4mlops/script
cm copy script get-cuda-devices .:get-rocm-devices
```
And then modify the `_cm.yaml`, `customize.py` and `run.sh` files as needed. 

You can then `git remote add` your forked URL, push the changes there and give a PR.

**Comment by Henryfzh** [comment]
Hi @arjunsuresh, is there a command to run the script directly using cm? I have tried running get-cuda-devices, but it also didn't work.
```
cm run script --tags=get,cuda-devices
INFO:root:* cm run script "get cuda-devices"
INFO:root:  * cm run script "get rocm _toolkit"

CM error: no scripts were found with above tags and variations

variation tags ['toolkit'] are not matching for the found script get-rocm with variations dict_keys([])
```

**Comment by arjunsuresh** [comment]
You need to edit the `tags` appropriately for `rocm` in `_cm.yaml`. The variations section can be fully removed. Then, you can do `cm reindex repo` followed by `cm run script --tags=get,rocm-devices` (here, `get`, and `rocm-devices` must be the tags of the newly added script).

**Comment by zixianwang2022** [comment]
@arjunsuresh We are getting unexpected results, are you able to assist us online? 
https://ucsd.zoom.us/j/92815982780?pwd=MUexHSsLBNpqC1ecBQYCVL5BzQEwXu.1

**Comment by Henryfzh** [comment]
@arjunsuresh After finishing the script, I had this error:

![image](https://github.com/user-attachments/assets/58361c69-16a6-4633-9a5d-1e99c6e80131)

My environment is using conda with python version 3.11

**Comment by arjunsuresh** [comment]
@zixianwang2022 sorry, I had slept by then. Saw your message in other thread- that should be because you are using an older fork of the inference repository. Please update the fork.

**Comment by arjunsuresh** [comment]
@Henryfzh Cool. `run.sh`, `customize.py`, `_cm.yaml` and in this case `detect.py` are the needed files for the CM script.

**Comment by arjunsuresh** [comment]
Hope this issue is resolved. Feel free to reopen if required.
